<div class="row">
    <div class="col-sm-6">
        <div class="pagination-info" aria-label="<?php echo $this->translate('Page navigation info'); ?>">
            <?php
            if ($this->totalItemCount > 0) {
                echo sprintf($this->translate('Showing %s to %s of %s entries'), $this->firstItemNumber, $this->lastItemNumber, $this->totalItemCount);
            } else {
                echo $this->translate('Showing 0 to 0 of 0 entries');
            }
            ?>
        </div>
    </div>
    <div class="col-sm-6">
        <?php if ($this->pageCount): ?>
            <nav aria-label="<?php echo $this->translate('Page navigation'); ?>">
                <ul class="pagination pagination-sm justify-content-center justify-content-md-end mb-0 mt-2 mt-md-0">
                    <?php if (isset($this->previous)): ?>
                        <!-- First page link -->
                        <li class="page-item">
                            <?php $options['query']['page'] = $this->first; ?>
                            <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                                <i class="fa fa-fw fa-angle-double-left"></i>
                                <span class="sr-only"><?php echo $this->translate('First'); ?></span>
                            </a>
                        </li>
                        <!-- Previous page link -->
                        <li class="page-item">
                            <?php $options['query']['page'] = $this->previous; ?>
                            <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                                <i class="fa fa-fw fa-angle-left"></i>
                                <span class="sr-only"><?php echo $this->translate('Previous'); ?></span>
                            </a>
                        </li>
                    <?php else: ?>
                        <!-- First page link -->
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">
                                <i class="fa fa-fw fa-angle-double-left"></i>
                                <span class="sr-only"><?php echo $this->translate('First'); ?></span>
                            </a>
                        </li>
                        <!-- Previous page link -->
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">
                                <i class="fa fa-fw fa-angle-left"></i>
                                <span class="sr-only"><?php echo $this->translate('Previous'); ?></span>
                            </a>
                        </li>
                    <?php endif; ?>

                    <!-- Numbered page links -->
                    <?php foreach ($this->pagesInRange as $page): ?>
                        <?php
                        if ($page != $this->current):
                            $options['query']['page'] = $page;
                            ?>
                            <li class="page-item">
                                <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                                    <?php echo $page; ?>
                                    <span class="sr-only">(<?php echo $this->translate('current'); ?>)</span>
                                </a>
                            </li>
                        <?php else: ?>
                            <li class="page-item active">
                                <span class="page-link">
                                    <?php echo $page; ?>
                                    <span class="sr-only">(<?php echo $this->translate('current'); ?>)</span>
                                </span>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>

                    <?php if (isset($this->previous)): ?>
                        <!-- Next page link -->
                        <li class="page-item">
                            <?php $options['query']['page'] = $this->next; ?>
                            <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                                <i class="fa fa-fw fa-angle-right"></i>
                                <span class="sr-only"><?php echo $this->translate('Next'); ?></span>
                            </a>
                        </li>
                        <!--  page link -->
                        <li class="page-item">
                            <?php $options['query']['page'] = $this->last; ?>
                            <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                                <i class="fa fa-fw fa-angle-double-right"></i>
                                <span class="sr-only"><?php echo $this->translate('Last'); ?></span>
                            </a>
                        </li>
                    <?php else: ?>
                        <!-- Next page link -->
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">
                                <i class="fa fa-fw fa-angle-right"></i>
                                <span class="sr-only"><?php echo $this->translate('Next'); ?></span>
                            </a>
                        </li>
                        <!-- Last page link -->
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">
                                <i class="fa fa-fw fa-angle-double-right"></i>
                                <span class="sr-only"><?php echo $this->translate('Last'); ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </nav>
        <?php endif; ?>
    </div>
</div>
