<?php if ($this->pageCount): ?>
    <nav aria-label="<?php echo $this->translate('Page navigation'); ?>">
        <ul class="pagination pagination-sm justify-content-center mb-0">
            <!-- First page link -->
            <?php
            if (isset($this->previous)):
                $options['query']['page'] = $this->first;
                ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                        <i class="fa fa-fw fa-angle-double-left"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">
                        <i class="fa fa-fw fa-angle-double-left"></i>
                    </span>
                </li>
            <?php endif; ?>
            <!-- Previous page link -->
            <?php
            if (isset($this->previous)):
                $options['query']['page'] = $this->previous;
                ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </span>
                </li>
            <?php endif; ?>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php
                if ($page != $this->current):
                    $options['query']['page'] = $page;
                    ?>
                    <li class="page-item">
                        <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item active">
                        <a class="page-link" href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php
            if (isset($this->next)):
                $options['query']['page'] = $this->next;
                ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                        <i class="fa fa-fw fa-angle-right"></i>
                    </a>
                </li>
            <?php else:?>
                <li class="page-item disabled">
                    <span class="page-link">
                        <i class="fa fa-fw fa-angle-right"></i>
                    </span>
                </li>
            <?php endif; ?>

            <!-- Last page link -->
            <?php
            if (isset($this->next)):
                $options['query']['page'] = $this->last;
                ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($route, $params, $options, $reuseMatchedParams); ?>">
                        <i class="fa fa-fw fa-angle-double-right"></i>
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">
                        <i class="fa fa-fw fa-angle-double-right"></i>
                    </span>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>
